"""Constants for the Arrowhead alarm integration."""

DEF_ENCODING = "ascii"
DEF_READ_LENGTH = 1024
DEF_REQUEST_DELIMITER = "\n"
DEFAULT_COMMAND_TIMEOUT = 5.0

AUTH_WELCOME_MSG = "Welcome"
AUTH_LOGIN_MSG = "login"
AUTH_PASSWORD_PROMPT = "password"

DEFAULT_PORT = 9000
DEFAULT_USER_ID = 1
DEFAULT_USER_PIN = 1234
DEFAULT_USERNAME = "admin"
DEFAULT_PASSWORD = "admin"
