"""Protocol constants."""

COMMAND_OK_PREFIX = "OK"
COMMAND_ERROR_PREFIX = "ERR"

CMD_VERSION = "Version"
CMD_MODE = "MODE"
CMD_STATUS = "STATUS"
CMD_DISARM = "DISARM"
CMD_ARM_AWAY = "ARMAWAY"
CMD_ARM_STAY = "ARMSTAY"

CMD_ARM_AREA_AWAY = "ARMAREA"
CMD_ARM_AREA_STAY = "STAYAREA"

CMD_BYPASS = "BYPASS"
CMD_UNBYPASS = "UNBYPASS"
CMD_OUTPUT_ON = "OUTPUTON"
CMD_OUTPUT_OFF = "OUTPUTOFF"
CMD_OUTPUT = "OUTPUT"
