"""Arrow Head Alarm Protocol module."""

from arrowhead_alarm.protocol.commands import (
    arm_area_collector,
    arm_button_collector,
    arm_user_collector,
    disarm_area_collector,
    disarm_user_collector,
    output_state_collector,
    mode_collector,
    set_output_collector,
    bypass_zone_collector,
    unbypass_zone_collector,
    version_response_collector,
)
from arrowhead_alarm.protocol.exceptions import (
    CommandError,
    CommandNotAllowedError,
    CommandNotUnderstoodError,
    InvalidParameterError,
    InvalidResponseError,
    ModeOperationUnsupportedError,
    ProtocolError,
    RxBufferOverflowError,
    TxBufferOverflowError,
    XModemSessionFailedError,
)
from arrowhead_alarm.protocol.models import (
    AlarmState,
    Area,
    ArmingMode,
    CommandPayload,
    ErrorResponse,
    Expander,
    OkResponse,
    Output,
    PanelState,
    PanelVersion,
    ProtocolMode,
    Request,
    VersionInfo,
    Zone,
)

__all__ = [
    "CommandPayload",
    "ProtocolMode",
    "ArmingMode",
    "Request",
    "PanelVersion",
    "VersionInfo",
    "OkResponse",
    "ErrorResponse",
    "PanelState",
    "Expander",
    "Output",
    "Zone",
    "AlarmState",
    "Area",
    # Commands
    "arm_area_collector",
    "arm_button_collector",
    "arm_user_collector",
    "disarm_area_collector",
    "disarm_user_collector",
    "output_state_collector",
    "mode_collector",
    "set_output_collector",
    "bypass_zone_collector",
    "unbypass_zone_collector",
    "version_response_collector",
    # Exceptions
    "ProtocolError",
    "CommandError",
    "ModeOperationUnsupportedError",
    "InvalidResponseError",
    "XModemSessionFailedError",
    "CommandNotUnderstoodError",
    "InvalidParameterError",
    "CommandNotAllowedError",
    "RxBufferOverflowError",
    "TxBufferOverflowError",
]
